# Generated by Django 2.2.6 on 2019-10-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('on', '0011_auto_20191030_1405'),
        ('user_profile', '0002_auto_20191030_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pickup_fact_date', 'Комплектовочные Факт Дата'), ('shipping_fact_date', 'Отгрузочные Факт Дата'), ('design_fact_date', 'Конструкторская документация Факт Дата'), ('material_fact_date', 'Материалы Факт Дата'), ('black_metal_fact_date', 'Черный метал Факт Дата'), ('galvanized_fact_date', 'Оцинкованный метал Факт Дата'), ('cast_iron_fact_date', 'Чугун Факт Дата')], default='pickup_fact_date', max_length=40)),
                ('date', models.DateField(verbose_name='Дата')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on.Order')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
    ]
