# Generated by Django 2.2.6 on 2019-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdate',
            name='must',
            field=models.BooleanField(default=True, verbose_name='Выдаются'),
        ),
    ]
