# Generated by Django 2.2.6 on 2019-11-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20191030_2225'),
        ('on', '0012_auto_20191101_1606'),
        ('incoming_documents', '0002_documentdate_must'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdate',
            name='must',
        ),
        migrations.CreateModel(
            name='DocumentMust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must', models.BooleanField(default=True, verbose_name='Не выдаются')),
                ('document_type', models.CharField(choices=[('pickup_fact_date', 'Комплектовочные Факт Дата'), ('shipping_fact_date', 'Отгрузочные Факт Дата'), ('design_fact_date', 'Конструкторская документация Факт Дата'), ('material_fact_date', 'Материалы Факт Дата'), ('black_metal_fact_date', 'Черный метал Факт Дата'), ('galvanized_fact_date', 'Оцинкованный метал Факт Дата'), ('cast_iron_fact_date', 'Чугун Факт Дата')], default='pickup_fact_date', max_length=40)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='on.Order')),
            ],
            options={
                'verbose_name': 'выдача документа',
                'verbose_name_plural': 'выдачу документа',
            },
        ),
    ]
