# Generated by Django 2.2.6 on 2019-11-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incoming_documents', '0003_auto_20191101_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentmust',
            options={'verbose_name': 'выдача документа', 'verbose_name_plural': 'выдача документа'},
        ),
    ]
