# Generated by Django 2.2.6 on 2019-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sn_no_amended',
            field=models.ManyToManyField(blank=True, null=True, related_name='ons', to='on.OfficeNote', verbose_name='№ СЗ'),
        ),
    ]
