# Generated by Django 2.2.6 on 2019-10-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0002_auto_20191026_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couterparty',
            options={'verbose_name': 'заказчик', 'verbose_name_plural': 'заказчики'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='couterparty',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='galvanized_metal_must',
            field=models.BooleanField(default=False, verbose_name='Чугун Выдается'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sn_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on', to='on.OfficeNote', verbose_name='№ СЗ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sn_no_amended',
            field=models.ManyToManyField(blank=True, null=True, related_name='ons', to='on.OfficeNote', verbose_name='№ СЗ с изменениями'),
        ),
    ]
