# Generated by Django 2.2.6 on 2019-10-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0005_auto_20191026_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='according_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Согласно КП №'),
        ),
        migrations.AlterField(
            model_name='order',
            name='personal_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='П/н'),
        ),
    ]
