# Generated by Django 2.2.6 on 2019-10-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0006_auto_20191027_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ProductType',
                'verbose_name_plural': 'ProductTypes',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pruduct_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='on.ProductType', verbose_name='Тип продукции'),
            preserve_default=False,
        ),
    ]
