# Generated by Django 2.2.6 on 2019-10-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0007_auto_20191027_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pruduct_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='on.ProductType', verbose_name='Тип продукции'),
        ),
    ]
