# Generated by Django 2.2.6 on 2019-10-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0008_auto_20191027_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='order_no',
        ),
    ]
