# Generated by Django 2.2.6 on 2019-10-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0009_auto_20191027_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='couterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='on.Couterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продукция'),
        ),
    ]
