# Generated by Django 2.2.6 on 2019-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0010_auto_20191028_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cast_iron_must',
            field=models.BooleanField(default=False, verbose_name='Чугун Выдается'),
        ),
        migrations.AlterField(
            model_name='order',
            name='galvanized_metal_must',
            field=models.BooleanField(default=False, verbose_name='Оцинкованный метал Выдается'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material_must',
            field=models.BooleanField(default=True, verbose_name='Материалы Выдаются'),
        ),
    ]
