# Generated by Django 2.2.6 on 2019-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0011_auto_20191030_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couterparty',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
