# Generated by Django 2.2.6 on 2019-11-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0012_auto_20191101_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(blank=True, default=False, verbose_name='Заказ Готов'),
        ),
    ]
