# Generated by Django 2.2.6 on 2019-11-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on', '0013_order_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Готовности заказа'),
        ),
    ]
