# Generated by Django 2.2.6 on 2019-11-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Код иконки')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'IconType',
                'verbose_name_plural': 'IconTypes',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('short_text', models.CharField(max_length=200, verbose_name='Короткий текст')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Полный текст')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('icon_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.IconType')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Historys',
            },
        ),
    ]
