# Generated by Django 2.2.6 on 2019-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'история', 'verbose_name_plural': 'истории'},
        ),
        migrations.AlterModelOptions(
            name='icontype',
            options={'verbose_name': 'тип иконки', 'verbose_name_plural': 'типы иконок'},
        ),
        migrations.AddField(
            model_name='icontype',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
