# Generated by Django 2.2.6 on 2019-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20191104_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='icon_text',
        ),
        migrations.AddField(
            model_name='history',
            name='color',
            field=models.CharField(default=1, max_length=50, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='icon',
            field=models.CharField(default=1, max_length=50, verbose_name='Код иконки'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IconType',
        ),
    ]
