# Generated by Django 2.2.6 on 2019-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(unique=True, verbose_name='ID')),
                ('in_sn_no', models.PositiveSmallIntegerField(blank=True, verbose_name='Порядковый номер')),
                ('shipment_from', models.DateField(blank=True, verbose_name='Отгрузка "от"')),
                ('shipment_before', models.DateField(blank=True, verbose_name='Отгрузка "до"')),
                ('product_name', models.CharField(max_length=200, verbose_name='Продукция')),
                ('counterparty', models.CharField(max_length=100, verbose_name='Контрагент')),
                ('order_no', models.PositiveIntegerField(blank=True, verbose_name='№ Заказа')),
                ('amount', models.FloatField(verbose_name='Кол-во')),
                ('sn_no', models.PositiveIntegerField(blank=True, verbose_name='№ СЗ')),
                ('sn_no_amended', models.CharField(blank=True, max_length=200, verbose_name='№ СЗ с изменениями')),
                ('sn_date', models.DateField(verbose_name='Дата СЗ')),
                ('sn_date_fact', models.DateField(verbose_name='Дата СЗ Факт')),
                ('pickup_plan_days', models.SmallIntegerField(blank=True, verbose_name='Комплектовочные План Дней')),
                ('pickup_plan_date', models.DateField(blank=True, verbose_name='Комплектовочные План Дата')),
                ('shipping_plan_days', models.SmallIntegerField(blank=True, verbose_name='Отгрузочные План Дней')),
                ('shipping_date_date', models.DateField(blank=True, verbose_name='Отгрузочные План Дата')),
                ('design_plan_days', models.SmallIntegerField(blank=True, verbose_name='Конструкторская документация План Дней')),
                ('design_plan_date', models.DateField(blank=True, verbose_name='Конструкторская документация План Дата')),
                ('material_plan_days', models.PositiveSmallIntegerField(blank=True, verbose_name='Материалы План Дней')),
                ('material_plan_date', models.DateField(blank=True, verbose_name='Материалы План Дата')),
                ('black_metal_plan_days', models.PositiveSmallIntegerField(blank=True, verbose_name='Черный метал План Дней')),
                ('black_metal_plan_date', models.DateField(blank=True, verbose_name='Черный метал План Дата')),
                ('galvanized_metal_plan_days', models.PositiveSmallIntegerField(blank=True, verbose_name='Оцинкованный метал План Дней')),
                ('galvanized_metal_plan_date', models.DateField(blank=True, verbose_name='Оцинкованный метал План Дата')),
                ('cast_iron_plan_days', models.PositiveSmallIntegerField(blank=True, verbose_name='Чугун План Дней')),
                ('cast_iron_plan_date', models.DateField(blank=True, verbose_name='Чугун План Дата')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
