# Generated by Django 2.2.6 on 2019-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='black_metal_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Черный метал План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='black_metal_plan_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Черный метал План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='cast_iron_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Чугун План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='cast_iron_plan_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Чугун План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='design_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конструкторская документация План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='design_plan_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Конструкторская документация План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='galvanized_metal_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Оцинкованный метал План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='galvanized_metal_plan_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оцинкованный метал План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='in_sn_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='material_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Материалы План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='material_plan_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Материалы План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='order_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№ Заказа'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='pickup_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Комплектовочные План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='pickup_plan_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Комплектовочные План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='shipment_before',
            field=models.DateField(blank=True, null=True, verbose_name='Отгрузка "до"'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='shipment_from',
            field=models.DateField(blank=True, null=True, verbose_name='Отгрузка "от"'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='shipping_date_date',
            field=models.DateField(blank=True, null=True, verbose_name='Отгрузочные План Дата'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='shipping_plan_days',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Отгрузочные План Дней'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='sn_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№ СЗ'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='sn_no_amended',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='№ СЗ с изменениями'),
        ),
    ]
