# Generated by Django 2.2.6 on 2019-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0002_auto_20191010_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='sn_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата СЗ'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='sn_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Дата СЗ Факт'),
        ),
    ]
