# Generated by Django 2.2.6 on 2019-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0003_auto_20191010_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenote',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Кол-во'),
        ),
    ]
