# Generated by Django 2.2.6 on 2019-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0004_auto_20191010_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicenote',
            options={'verbose_name': 'служебную записку', 'verbose_name_plural': 'служебные записки'},
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='counterparty',
            field=models.CharField(max_length=255, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='sn_no_amended',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ СЗ с изменениями'),
        ),
    ]
