# Generated by Django 2.2.6 on 2019-10-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0006_auto_20191014_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operativenote',
            old_name='shipping_date_date',
            new_name='shipping_plan_date',
        ),
        migrations.RenameField(
            model_name='servicenote',
            old_name='shipping_date_date',
            new_name='shipping_plan_date',
        ),
    ]
