# Generated by Django 2.2.6 on 2019-10-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0007_auto_20191014_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(unique=True, verbose_name='ID')),
                ('ready', models.BooleanField(blank=True, null=True, verbose_name='Готово')),
                ('ready_date', models.DateField(blank=True, null=True, verbose_name='Готово Дата')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'готовый заказ',
                'verbose_name_plural': 'готовые заказы',
                'ordering': ['pk'],
            },
        ),
    ]
