# Generated by Django 2.2.6 on 2019-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0008_readyorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='InDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_id', models.IntegerField(unique=True, verbose_name='ID')),
                ('dispatcher', models.CharField(max_length=255, verbose_name='Диспетчер')),
                ('pickup_issue', models.BooleanField(blank=True, null=True, verbose_name='Комплектовочные Выдача')),
                ('pickup_date_1', models.DateField(blank=True, null=True, verbose_name='Комплектовочные Дата 1')),
                ('pickup_date_2', models.DateField(blank=True, null=True, verbose_name='Комплектовочные Дата 2')),
                ('pickup_date_3', models.DateField(blank=True, null=True, verbose_name='Комплектовочные Дата 3')),
                ('shipping_issue', models.BooleanField(blank=True, null=True, verbose_name='Отгрузочные Выдача')),
                ('shipping_date_1', models.DateField(blank=True, null=True, verbose_name='Отгрузочные Дата 1')),
                ('shipping_date_2', models.DateField(blank=True, null=True, verbose_name='Отгрузочные Дата 2')),
                ('shipping_date_3', models.DateField(blank=True, null=True, verbose_name='Отгрузочные Дата 3')),
                ('design_issue', models.BooleanField(blank=True, null=True, verbose_name='Конструкторские Выдача')),
                ('design_date_1', models.DateField(blank=True, null=True, verbose_name='Конструкторские Дата 1')),
                ('design_date_2', models.DateField(blank=True, null=True, verbose_name='Конструкторские Дата 2')),
                ('design_date_3', models.DateField(blank=True, null=True, verbose_name='Конструкторские Дата 3')),
                ('drawings_issue', models.BooleanField(blank=True, null=True, verbose_name='Изменение чертежей Выдача')),
                ('drawings_date_1', models.DateField(blank=True, null=True, verbose_name='Изменение чертежей Дата 1')),
                ('drawings_date_2', models.DateField(blank=True, null=True, verbose_name='Изменение чертежей Дата 2')),
                ('drawings_date_3', models.DateField(blank=True, null=True, verbose_name='Изменение чертежей Дата 3')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'график документации',
                'verbose_name_plural': 'график документации',
                'ordering': ['pk'],
            },
        ),
    ]
