# Generated by Django 2.2.6 on 2019-10-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0009_indocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indocument',
            name='in_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
