# Generated by Django 2.2.6 on 2019-10-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0011_auto_20191021_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='nomenclature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='shop_recipient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЦехПолучатель'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='stock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='warehouse_recipient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СкладПолучатель'),
        ),
    ]
