# Generated by Django 2.2.6 on 2019-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0012_auto_20191021_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='document',
            field=models.CharField(max_length=255, unique=True, verbose_name='Документ'),
        ),
    ]
