# Generated by Django 2.2.6 on 2019-10-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0014_auto_20191022_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='order_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЗаказНомер'),
        ),
    ]
