# Generated by Django 2.2.6 on 2019-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0016_shedulefile_shedulefileerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_no', models.CharField(blank=True, max_length=245, null=True)),
                ('order_no', models.CharField(blank=True, max_length=245, null=True)),
                ('knot', models.CharField(blank=True, max_length=245, null=True)),
                ('name', models.CharField(blank=True, max_length=245, null=True)),
                ('operation', models.CharField(blank=True, max_length=245, null=True)),
                ('amount_knot', models.CharField(blank=True, max_length=245, null=True)),
                ('amount_product', models.CharField(blank=True, max_length=245, null=True)),
                ('amount_order', models.CharField(blank=True, max_length=245, null=True)),
                ('amount_array', models.CharField(blank=True, max_length=245, null=True)),
                ('material', models.CharField(blank=True, max_length=245, null=True)),
                ('size', models.CharField(blank=True, max_length=245, null=True)),
                ('size_workpiece', models.CharField(blank=True, max_length=245, null=True)),
                ('shop_path', models.CharField(blank=True, max_length=245, null=True)),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
