# Generated by Django 2.2.6 on 2019-10-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_note', '0017_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='amount_array',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Кол-во Массив'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='amount_knot',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Кол-во Узел'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='amount_order',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Кол-во Заказ'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='amount_product',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Кол-во Изделие'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='in_no',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Внутренний номер'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='knot',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Узел'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='material',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='name',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='operation',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='order_no',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Заказ №'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='shop_path',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Росцеховка'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='size',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='size_workpiece',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Размер заготовки'),
        ),
    ]
