# Generated by Django 2.2.6 on 2019-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname_small',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия, инициалы'),
        ),
    ]
